"""create attendance tabel

Revision ID: 246dae9c2444
Revises: 75445c8bacf4
Create Date: 2022-07-19 23:53:05.074638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246dae9c2444'
down_revision = '75445c8bacf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checkin_at', sa.DateTime(), nullable=True),
    sa.Column('checkout_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_checkin_at'), 'attendance', ['checkin_at'], unique=False)
    op.create_index(op.f('ix_attendance_checkout_at'), 'attendance', ['checkout_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_checkout_at'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_checkin_at'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
